export const API_ENDPOINTS = {
  system: {
    health: '/health',
  },
  auth: {
    register: '/api/v1/antojados/auth/register',
    registerEmployee: '/api/v1/antojados/auth/register-employee',
    login: '/api/v1/antojados/auth/login',
    passwordRecoveryRequest: '/api/v1/antojados/auth/password-recovery/request',
    passwordRecoveryVerify: '/api/v1/antojados/auth/password-recovery/verify',
    passwordRecoveryReset: '/api/v1/antojados/auth/password-recovery/reset',
    profile: (userId: string) => `/api/v1/antojados/auth/profile/${encodeURIComponent(userId)}`,
    explorers: '/api/v1/antojados/auth/explorers',
    explorersActivity: '/api/v1/antojados/auth/explorers/activity',
    explorer: (userId: string) => `/api/v1/antojados/auth/explorers/${encodeURIComponent(userId)}`,
    explorerAssociations: (userId: string) => `/api/v1/antojados/auth/explorers/${encodeURIComponent(userId)}/associations`,
    explorerAssociation: (userId: string, associationId: string) =>
      `/api/v1/antojados/auth/explorers/${encodeURIComponent(userId)}/associations/${encodeURIComponent(associationId)}`,
    explorerActivity: (userId: string) => `/api/v1/antojados/auth/explorers/${encodeURIComponent(userId)}/activity`,
  },
  instance: {
    me: '/api/v1/antojados/instancias/me/info',
  },
  equipo: {
    myTenant: '/api/v1/antojados/equipo/mi-tenant',
    usuarios: '/api/v1/antojados/equipo/usuarios',
    usuarioPerfil: (tenantUserId: string) => `/api/v1/antojados/equipo/usuarios/${encodeURIComponent(tenantUserId)}/perfil`,
    usuarioRevocar: (tenantUserId: string) => `/api/v1/antojados/equipo/usuarios/${encodeURIComponent(tenantUserId)}/revocar`,
    transferAdmin: '/api/v1/antojados/equipo/usuarios/transferir-admin',
    perfiles: '/api/v1/antojados/equipo/perfiles',
    invitar: '/api/v1/antojados/equipo/invitar',
    invitaciones: '/api/v1/antojados/equipo/invitaciones',
    invitacion: (inviteCode: string) => `/api/v1/antojados/equipo/invitacion/${encodeURIComponent(inviteCode)}`,
    invitacionDetalle: (invitationId: string) => `/api/v1/antojados/equipo/invitaciones/${encodeURIComponent(invitationId)}`,
    redimir: '/api/v1/antojados/equipo/redimir',
    asignaciones: (tenantUserId: string) => `/api/v1/antojados/equipo/asignaciones/${encodeURIComponent(tenantUserId)}`,
    asignacionesSeed: (tenantUserId: string) => `/api/v1/antojados/equipo/asignaciones/${encodeURIComponent(tenantUserId)}/seed`,
  },
  sponsors: {
    myInstance: '/api/v1/antojados/instancias/me/info',
    setupBusiness: (instanceId: string) => `/api/v1/antojados/biz/instancias/${encodeURIComponent(instanceId)}/setup/business`,
    setupRepresentative: (instanceId: string) => `/api/v1/antojados/biz/instancias/${encodeURIComponent(instanceId)}/setup/representative`,
    setupBilling: (instanceId: string) => `/api/v1/antojados/biz/instancias/${encodeURIComponent(instanceId)}/setup/billing`,
    expedienteUpload: (instanceId: string) => `/api/v1/antojados/biz/instancias/${encodeURIComponent(instanceId)}/expediente/upload`,
  },
  tenants: {
    list: '/api/v1/antojados/gt/tenants',
    detail: (tenantId: string) => `/api/v1/antojados/gt/tenants/${encodeURIComponent(tenantId)}`,
    activate: (tenantId: string) => `/api/v1/antojados/gt/tenants/${encodeURIComponent(tenantId)}/activate`,
    suspend: (tenantId: string) => `/api/v1/antojados/gt/tenants/${encodeURIComponent(tenantId)}/suspend`,
    reactivate: (tenantId: string) => `/api/v1/antojados/gt/tenants/${encodeURIComponent(tenantId)}/reactivate`,
    expediente: (tenantId: string) => `/api/v1/antojados/gt/tenants/${encodeURIComponent(tenantId)}/expediente`,
    expedienteReview: (tenantId: string, docId: string) =>
      `/api/v1/antojados/gt/tenants/${encodeURIComponent(tenantId)}/expediente/${encodeURIComponent(docId)}/review`,
  },
  places: {
    list: '/api/v1/antojados/places',
    searchGooglePlaces: '/api/v1/antojados/places/search-gplaces',
    detail: (placeId: string) => `/api/v1/antojados/places/${encodeURIComponent(placeId)}`,
    posts: (placeId: string) => `/api/v1/antojados/places/${encodeURIComponent(placeId)}/posts`,
    ratingsSummary: (placeId: string) => `/api/v1/antojados/places/${encodeURIComponent(placeId)}/ratings-summary`,
  },
  geo: {
    scopes: '/api/v1/antojados/geo/scopes',
    citySearch: '/api/v1/antojados/geo/cities/search',
    resolve: '/api/v1/antojados/geo/resolve',
  },
  rankings: {
    topPlaces: '/api/v1/antojados/top-places',
    sponsorMetrics: '/api/v1/antojados/analytics/sponsor-metrics',
    userSummary: '/api/v1/antojados/analytics/user-summary',
  },
  media: {
    // Media Engine V3 endpoints (proxy Nginx: /api/media/* → localhost:4100)
    v3: {
      requests: '/api/media/requests',
      rightsOrigin: (mediaId: string) => `/api/media/${encodeURIComponent(mediaId)}/rights-origin`,
      original: (mediaId: string) => `/api/media/${encodeURIComponent(mediaId)}/original`,
      readyPayload: (mediaId: string) => `/api/media/${encodeURIComponent(mediaId)}/ready-payload`,
    },
  },
  efirma: {
    create: '/api/v1/antojados/gt/efirma/create',
    sendActivation: '/api/v1/antojados/gt/efirma/send-activation',
    acceptActivation: '/api/v1/antojados/gt/efirma/accept-activation',
    authorizeAction: '/api/v1/antojados/gt/efirma/authorize-action',
    status: '/api/v1/antojados/gt/efirma/status',
  },
  modulos: {
    catalog: (instanceId: string) => `/api/v1/antojados/gt/instances/${encodeURIComponent(instanceId)}/modules/catalog`,
    operations: (instanceId: string) => `/api/v1/antojados/gt/instances/${encodeURIComponent(instanceId)}/modules/operations`,
    audit: (instanceId: string) => `/api/v1/antojados/gt/instances/${encodeURIComponent(instanceId)}/modules/audit`,
  },
  gt: {
    dimensions: '/api/v1/antojados/gt/dimensions',
    subDimensions: '/api/v1/antojados/gt/sub-dimensions',
    template: (code: string) => `/api/v1/antojados/gt/templates/${encodeURIComponent(code)}`,
    checkedDimensions: (instanceId: string) => `/api/v1/antojados/gt/instances/${encodeURIComponent(instanceId)}/checked/dimensions`,
    checkedSubDimensions: (instanceId: string) => `/api/v1/antojados/gt/instances/${encodeURIComponent(instanceId)}/checked/sub-dimensions`,
    checkedEvents: (instanceId: string) => `/api/v1/antojados/gt/instances/${encodeURIComponent(instanceId)}/checked/events`,
  },
  bizPosts: {
    feed: '/api/v1/antojados/feed',
    create: '/api/v1/antojados/biz/posts',
    detail: (bizPostId: string) => `/api/v1/antojados/biz/posts/${encodeURIComponent(bizPostId)}`,
  },
  socialPosts: {
    feed: '/api/v1/antojados/feed',
    create: '/api/v1/antojados/posts',
    detail: (postId: string) => `/api/v1/antojados/posts/${encodeURIComponent(postId)}`,
    syncEvents: '/api/v1/antojados/sync/events',
    following: (userId: string) => `/api/v1/antojados/social/following/${encodeURIComponent(userId)}`,
    followers: (userId: string) => `/api/v1/antojados/social/followers/${encodeURIComponent(userId)}`,
    saves: (userId: string) => `/api/v1/antojados/social/saves/${encodeURIComponent(userId)}`,
  },
  rewards: {
    campaigns: '/api/v1/antojados/rewards/campaigns',
    campaignDetail: (campaignId: string) => `/api/v1/antojados/rewards/campaigns/${encodeURIComponent(campaignId)}`,
    eligibility: '/api/v1/antojados/rewards/eligibility',
    redeem: '/api/v1/antojados/rewards/redeem',
    redemptions: (userId: string) => `/api/v1/antojados/rewards/redemptions/${encodeURIComponent(userId)}`,
  },
  // Publications (DocumentPackage vía API Gateway → Explorer)
  publications: {
    byChannel: (channel: string) => `/api/v1/antojados/publications/by-channel/${encodeURIComponent(channel)}`,
    bySponsor: (sponsorId: string) => `/api/v1/antojados/publications/by-sponsor/${encodeURIComponent(sponsorId)}`,
    byPost: (externalPostId: string) => `/api/v1/antojados/publications/by-post/${encodeURIComponent(externalPostId)}`,
    create: '/api/v1/antojados/publications',
  },
} as const
